DATA:
  MAPS:
    TEST:
    - scene-0162
    - scene-0220
    - scene-0623
    - scene-0744
    - scene-0553
    - scene-0534
    - scene-0499
    - scene-0099
    - scene-0389
    - scene-0917
    - scene-0277
    - scene-0093
    - scene-0752
    - scene-0269
    - scene-0482
    - scene-0741
    TRAIN:
    - scene-0613
    - scene-0207
    - scene-0403
    - scene-0842
    - scene-0505
    - scene-0014
    - scene-0548
    - scene-0687
    - scene-0497
    - scene-0417
    - scene-0275
    - scene-0227
    - scene-0270
    - scene-0146
    - scene-0004
    - scene-0018
    - scene-0396
    - scene-0762
    - scene-0491
    - scene-0125
    - scene-0829
    - scene-0274
    - scene-0175
    - scene-0172
    - scene-0019
    - scene-0071
    - scene-0187
    - scene-0413
    - scene-0340
    - scene-0937
    - scene-0935
    - scene-0106
    - scene-0410
    - scene-0226
    - scene-0607
    - scene-0260
    - scene-0838
    - scene-0282
    - scene-0129
    - scene-0283
    - scene-0008
    - scene-0407
    - scene-0109
    - scene-0943
    - scene-0033
    - scene-0107
    - scene-0001
    - scene-0402
    - scene-0418
    - scene-0174
    - scene-0110
    - scene-0130
    - scene-0397
    - scene-0009
    - scene-0251
    - scene-0610
    - scene-0279
    - scene-0165
    - scene-0026
    - scene-0231
    - scene-0830
    - scene-0128
    - scene-0271
    - scene-0398
    - scene-0173
    - scene-0761
    - scene-0746
    - scene-0161
    - scene-0783
    - scene-0241
    - scene-0206
    - scene-0369
    - scene-0012
    - scene-0045
    - scene-0933
    - scene-0006
    - scene-0002
    - scene-0767
    - scene-0042
    - scene-0247
    - scene-0740
    - scene-0835
    - scene-0627
    - scene-0177
    - scene-0528
    - scene-0233
    - scene-0097
    - scene-0028
    - scene-0751
    - scene-0768
    - scene-0565
    - scene-0236
    - scene-0496
    - scene-0549
    - scene-0222
    - scene-0166
    - scene-0764
    - scene-0297
    - scene-0180
    - scene-0031
    - scene-0069
    - scene-0108
    - scene-0030
    - scene-0315
    - scene-0168
    - scene-0307
    - scene-0152
    - scene-0940
    - scene-0506
    - scene-0256
    - scene-0791
    - scene-0932
    - scene-0504
    - scene-0170
    - scene-0769
    - scene-0176
    - scene-0230
    - scene-0406
    - scene-0164
    - scene-0273
    - scene-0041
    - scene-0096
    - scene-0412
    - scene-0167
    - scene-0624
    - scene-0714
    VAL:
    - scene-0163
    - scene-0388
    - scene-0237
    - scene-0224
    - scene-0757
    - scene-0184
    - scene-0840
    - scene-0229
    - scene-0178
    - scene-0500
    - scene-0278
    - scene-0228
    - scene-0834
    - scene-0614
    - scene-0035
    - scene-0942
  NUM_WORKER: 4
  SHUFFLE: true
  SPLIT:
    TEST:
    - scene-0665
    - scene-0218
    - scene-0219
    - scene-0695
    - scene-0901
    - scene-0530
    - scene-0570
    - scene-0464
    - scene-0573
    - scene-0515
    - scene-0292
    - scene-0678
    - scene-0487
    - scene-0472
    - scene-0679
    - scene-0643
    - scene-0911
    - scene-1033
    - scene-0039
    - scene-0984
    - scene-0147
    - scene-0359
    - scene-0372
    - scene-0126
    - scene-0968
    - scene-0484
    - scene-0461
    - scene-0669
    - scene-0588
    - scene-0286
    - scene-0701
    - scene-0703
    - scene-0533
    - scene-0143
    - scene-0281
    - scene-0459
    - scene-0585
    - scene-0285
    - scene-0526
    TRAIN:
    - scene-0893
    - scene-0636
    - scene-1050
    - scene-1022
    - scene-1023
    - scene-0520
    - scene-0190
    - scene-0734
    - scene-0606
    - scene-0730
    - scene-0877
    - scene-0306
    - scene-0878
    - scene-0305
    - scene-0880
    - scene-0868
    - scene-0476
    - scene-0719
    - scene-0726
    - scene-0873
    - scene-1057
    - scene-0355
    - scene-0356
    - scene-0981
    - scene-0982
    - scene-0017
    - scene-0158
    - scene-0358
    - scene-0671
    - scene-0463
    - scene-0704
    - scene-0243
    - scene-0554
    - scene-0288
    - scene-0095
    - scene-0672
    - scene-0949
    - scene-0021
    - scene-0192
    - scene-0353
    - scene-0043
    - scene-0046
    - scene-0159
    - scene-0061
    - scene-0650
    - scene-0538
    - scene-0539
    - scene-0686
    - scene-0719
    - scene-0371
    - scene-0967
    - scene-1012
    - scene-0980
    - scene-0072
    - scene-0210
    - scene-0449
    - scene-0661
    - scene-0945
    - scene-0660
    - scene-0448
    - scene-1036
    - scene-0921
    - scene-1056
    - scene-0477
    - scene-0478
    - scene-1003
    - scene-1001
    - scene-0303
    - scene-0514
    - scene-1054
    - scene-0670
    - scene-0812
    - scene-0898
    - scene-0301
    - scene-0689
    - scene-1017
    - scene-0349
    - scene-0711
    - scene-0374
    - scene-0373
    - scene-0375
    - scene-0990
    - scene-0584
    - scene-0457
    - scene-0050
    - scene-0155
    - scene-1053
    - scene-0523
    - scene-0508
    - scene-0550
    - scene-0626
    - scene-0434
    - scene-0196
    - scene-0367
    - scene-0920
    - scene-0304
    - scene-0876
    - scene-0547
    - scene-0875
    - scene-0054
    - scene-0038
    - scene-1049
    - scene-1058
    - scene-0663
    - scene-0212
    - scene-0450
    - scene-0509
    - scene-0263
    - scene-0086
    - scene-0451
    - scene-0360
    - scene-0651
    - scene-0380
    - scene-0379
    - scene-0154
    - scene-0238
    - scene-0239
    - scene-0300
    - scene-0479
    - scene-0342
    - scene-0495
    - scene-0494
    - scene-0869
    - scene-0885
    - scene-0139
    - scene-0347
    - scene-0092
    - scene-0333
    - scene-0265
    - scene-0062
    - scene-0953
    - scene-0676
    - scene-0710
    - scene-1013
    - scene-0989
    - scene-0971
    - scene-0988
    - scene-0972
    - scene-0928
    - scene-0915
    - scene-0662
    - scene-0211
    - scene-0537
    - scene-0536
    - scene-0571
    - scene-0532
    - scene-0218
    - scene-0810
    - scene-0809
    - scene-0591
    - scene-0560
    - scene-0559
    - scene-0811
    - scene-0590
    - scene-0561
    - scene-0252
    - scene-0068
    - scene-0657
    - scene-0963
    - scene-0309
    - scene-0140
    - scene-0055
    - scene-0120
    - scene-0003
    - scene-0133
    - scene-0999
    - scene-1000
    - scene-0022
    - scene-0049
    - scene-0983
    - scene-0544
    - scene-0124
    - scene-0966
    - scene-0712
    - scene-0293
    - scene-0683
    - scene-0488
    - scene-0711
    - scene-0566
    - scene-0525
    - scene-0927
    - scene-0864
    - scene-0816
    - scene-0929
    - scene-0568
    - scene-0295
    - scene-0716
    - scene-0707
    - scene-0244
    - scene-0321
    - scene-0673
    - scene-0468
    - scene-0956
    - scene-0533
    - scene-0572
    - scene-0545
    - scene-0803
    - scene-0594
    - scene-0478
    - scene-0103
    - scene-0869
    - scene-0115
    - scene-0341
    - scene-0494
    - scene-0493
    - scene-0871
    - scene-0870
    - scene-0735
    - scene-0597
    - scene-0667
    - scene-0697
    - scene-0481
    - scene-0458
    - scene-0284
    - scene-0111
    - scene-0255
    - scene-0440
    - scene-0254
    - scene-0063
    - scene-0078
    - scene-0541
    - scene-0475
    - scene-0916
    - scene-0420
    - scene-0961
    - scene-0330
    - scene-0658
    - scene-0262
    - scene-0598
    - scene-0959
    - scene-0960
    - scene-1004
    - scene-1034
    - scene-0424
    - scene-0655
    - scene-0204
    - scene-0444
    - scene-0081
    - scene-0066
    - scene-0080
    - scene-0443
    - scene-0065
    - scene-0203
    - scene-0351
    - scene-0378
    - scene-0426
    - scene-1007
    - scene-0521
    - scene-0815
    - scene-0586
    - scene-0483
    - scene-1031
    - scene-0992
    - scene-0905
    - scene-0519
    - scene-0331
    - scene-0447
    - scene-0084
    - scene-0083
    - scene-0582
    - scene-0546
    - scene-0804
    - scene-0073
    - scene-0551
    - scene-0213
    - scene-0087
    - scene-0452
    - scene-0710
    - scene-0675
    - scene-0709
    - scene-0471
    - scene-0291
    - scene-1052
    - scene-0513
    - scene-0091
    - scene-0352
    - scene-0963
    - scene-0368
    - scene-0962
    - scene-0555
    - scene-0465
    - scene-0337
    - scene-0706
    - scene-0705
    - scene-0672
    - scene-0288
    - scene-0243
    - scene-1055
    - scene-0079
    - scene-0653
    - scene-0442
    - scene-0329
    - scene-0654
    - scene-0902
    - scene-0296
    VAL:
    - scene-0075
    - scene-0511
    - scene-0332
    - scene-0455
    - scene-0090
    - scene-0639
    - scene-0640
    - scene-0688
    - scene-0619
    - scene-0242
    - scene-0587
    - scene-0700
    - scene-0576
    - scene-0919
    - scene-1019
    - scene-0245
    - scene-0674
    - scene-0290
    - scene-0866
    - scene-0930
    - scene-1043
    - scene-0931
    - scene-0888
    - scene-0890
    - scene-0612
    - scene-0518
    - scene-0889
    - scene-0148
    - scene-0308
    - scene-0469
    - scene-0485
    - scene-0708
    - scene-0098
    - scene-1042
    - scene-0863
    - scene-0926
    - scene-0894
    - scene-0376
    - scene-0134
    - scene-0428
EXPERIMENT:
  ID: NUSCENES_TEST_0218_MAP-0162_map-parsing_high_kdtree_thresh
FILTER:
  THRESHOLD: 0.84
MODEL:
  RADAR_FEATURES: true
  VOXEL_SIZE: 0.1
TRAIN:
  AUGMENTATION: false
  BATCH_SIZE: 1
  LR: 0.001
  LR_DECAY: 0.99
  LR_EPOCH: 100
  MAP: ''
  MAX_EPOCH: 100
  WEIGHT_DECAY: 0.0001
